"""mail verification

Revision ID: 06151e8b400d
Revises: 3d78c57ebe36
Create Date: 2022-07-20 15:05:08.633472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06151e8b400d'
down_revision = '3d78c57ebe36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    # ### end Alembic commands ###
